# Generated by Django 5.2.14 on 2026-05-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(default='My Look', max_length=128)),
                ('foundation_color', models.CharField(blank=True, max_length=9)),
                ('lipstick_color', models.CharField(blank=True, max_length=9)),
                ('blush_color', models.CharField(blank=True, max_length=9)),
                ('contour_color', models.CharField(blank=True, max_length=9)),
                ('foundation_opacity', models.FloatField(default=0.2)),
                ('lipstick_opacity', models.FloatField(default=0.45)),
                ('blush_opacity', models.FloatField(default=0.3)),
                ('contour_opacity', models.FloatField(default=0.25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('undertone', models.CharField(max_length=16)),
                ('surface_tone', models.CharField(max_length=16)),
                ('lightness', models.FloatField()),
                ('lab_l', models.FloatField()),
                ('lab_a', models.FloatField()),
                ('lab_b', models.FloatField()),
                ('recommendations', models.JSONField(default=dict)),
                ('mode', models.CharField(default='automatic', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
