# Generated by Django 5.2.14 on 2026-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=128)),
                ('image', models.ImageField(upload_to='captures/')),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('makeup_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_data', models.CharField(db_index=True, max_length=512)),
                ('product_name', models.CharField(blank=True, max_length=256)),
                ('colour_name', models.CharField(blank=True, max_length=64)),
                ('colour_hex', models.CharField(blank=True, max_length=9)),
                ('colour_rgb', models.CharField(blank=True, max_length=32)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('raw_content', models.TextField(blank=True)),
                ('scanned_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='favoritelook',
            name='bindi_color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='favoritelook',
            name='bindi_opacity',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='favoritelook',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='skinanalysisresult',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
