# Generated by Django 5.2.14 on 2026-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_capturedphoto_scannedproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
